# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guiRpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guiRpc.proto',
  package='guiRpc',
  syntax='proto3',
  serialized_options=_b('\n\032io.grpc.labDataTool.guiRpcB\013GuiRpcProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0cguiRpc.proto\x12\x06guiRpc\"\x15\n\x06STATUS\x12\x0b\n\x03ret\x18\x01 \x01(\t\"\x98\x01\n\x0bSampleArray\x12.\n\x06Sparam\x18\x01 \x01(\x0e\x32\x1e.guiRpc.SampleArray.SParamType\x12\x13\n\x0b\x64\x61ta_length\x18\x02 \x01(\x05\x12\x12\n\ndata_bytes\x18\x03 \x01(\x0c\"0\n\nSParamType\x12\x07\n\x03S11\x10\x00\x12\x07\n\x03S21\x10\x01\x12\x07\n\x03S12\x10\x02\x12\x07\n\x03S22\x10\x03\"T\n\x0f\x45xperimentSetup\x12\x10\n\x08operator\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07\x66reqLow\x18\x03 \x01(\x02\x12\x10\n\x08\x66reqHigh\x18\x04 \x01(\x02\x32I\n\x06GuiRpc\x12?\n\x0bstartSample\x12\x17.guiRpc.ExperimentSetup\x1a\x13.guiRpc.SampleArray\"\x00\x30\x01\x42\x31\n\x1aio.grpc.labDataTool.guiRpcB\x0bGuiRpcProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)



_SAMPLEARRAY_SPARAMTYPE = _descriptor.EnumDescriptor(
  name='SParamType',
  full_name='guiRpc.SampleArray.SParamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S11', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S21', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S12', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S22', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=152,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_SAMPLEARRAY_SPARAMTYPE)


_STATUS = _descriptor.Descriptor(
  name='STATUS',
  full_name='guiRpc.STATUS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='guiRpc.STATUS.ret', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=45,
)


_SAMPLEARRAY = _descriptor.Descriptor(
  name='SampleArray',
  full_name='guiRpc.SampleArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Sparam', full_name='guiRpc.SampleArray.Sparam', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_length', full_name='guiRpc.SampleArray.data_length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_bytes', full_name='guiRpc.SampleArray.data_bytes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAMPLEARRAY_SPARAMTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=200,
)


_EXPERIMENTSETUP = _descriptor.Descriptor(
  name='ExperimentSetup',
  full_name='guiRpc.ExperimentSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator', full_name='guiRpc.ExperimentSetup.operator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='guiRpc.ExperimentSetup.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freqLow', full_name='guiRpc.ExperimentSetup.freqLow', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freqHigh', full_name='guiRpc.ExperimentSetup.freqHigh', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=286,
)

_SAMPLEARRAY.fields_by_name['Sparam'].enum_type = _SAMPLEARRAY_SPARAMTYPE
_SAMPLEARRAY_SPARAMTYPE.containing_type = _SAMPLEARRAY
DESCRIPTOR.message_types_by_name['STATUS'] = _STATUS
DESCRIPTOR.message_types_by_name['SampleArray'] = _SAMPLEARRAY
DESCRIPTOR.message_types_by_name['ExperimentSetup'] = _EXPERIMENTSETUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

STATUS = _reflection.GeneratedProtocolMessageType('STATUS', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.STATUS)
  })
_sym_db.RegisterMessage(STATUS)

SampleArray = _reflection.GeneratedProtocolMessageType('SampleArray', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEARRAY,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.SampleArray)
  })
_sym_db.RegisterMessage(SampleArray)

ExperimentSetup = _reflection.GeneratedProtocolMessageType('ExperimentSetup', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENTSETUP,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.ExperimentSetup)
  })
_sym_db.RegisterMessage(ExperimentSetup)


DESCRIPTOR._options = None

_GUIRPC = _descriptor.ServiceDescriptor(
  name='GuiRpc',
  full_name='guiRpc.GuiRpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=288,
  serialized_end=361,
  methods=[
  _descriptor.MethodDescriptor(
    name='startSample',
    full_name='guiRpc.GuiRpc.startSample',
    index=0,
    containing_service=None,
    input_type=_EXPERIMENTSETUP,
    output_type=_SAMPLEARRAY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GUIRPC)

DESCRIPTOR.services_by_name['GuiRpc'] = _GUIRPC

# @@protoc_insertion_point(module_scope)
