# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guiRpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guiRpc.proto',
  package='guiRpc',
  syntax='proto3',
  serialized_options=_b('\n\032io.grpc.labDataTool.guiRpcB\013GuiRpcProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0cguiRpc.proto\x12\x06guiRpc\"4\n\tByteBlock\x12\x13\n\x0b\x64\x61ta_length\x18\x02 \x01(\x05\x12\x12\n\ndata_bytes\x18\x01 \x01(\x0c\"\x87\x01\n\x08\x43mdReply\x12)\n\x07\x63mdType\x18\x01 \x01(\x0e\x32\x18.guiRpc.CmdReply.CmdType\x12\x10\n\x08\x63mdReply\x18\x02 \x01(\t\">\n\x07\x43mdType\x12\x07\n\x03Nop\x10\x00\x12\r\n\tstatusStr\x10\x01\x12\x0b\n\x07\x64\x61taStr\x10\x02\x12\x0e\n\ndataBinary\x10\x03\"\x1d\n\nLabCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\xc9\x01\n\x0bSampleArray\x12\x0f\n\x07Meas_id\x18\x01 \x01(\x05\x12.\n\x06Sparam\x18\x02 \x01(\x0e\x32\x1e.guiRpc.SampleArray.SParamType\x12\x1f\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x11.guiRpc.ByteBlock\x12\x1d\n\x02\x66\x66\x18\x04 \x01(\x0b\x32\x11.guiRpc.ByteBlock\"9\n\nSParamType\x12\x07\n\x03Nop\x10\x00\x12\x07\n\x03S11\x10\x01\x12\x07\n\x03S21\x10\x02\x12\x07\n\x03S12\x10\x04\x12\x07\n\x03S22\x10\x08\"\xbe\x03\n\x0f\x45xperimentSetup\x12\x0f\n\x07Meas_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x45NADataMode\x18\x02 \x01(\x05\x12\x16\n\x0eNumberOfPoints\x18\x03 \x01(\x05\x12\x11\n\tfreq_STAR\x18\x04 \x01(\x02\x12\x11\n\tfreq_STOP\x18\x05 \x01(\x02\x12\x11\n\tfreq_CENT\x18\x06 \x01(\x02\x12\x11\n\tfreq_SPAN\x18\x07 \x01(\x02\x12\x12\n\ndataFormat\x18\x08 \x01(\x05\x12\x33\n\x07Sparam1\x18\t \x01(\x0e\x32\".guiRpc.ExperimentSetup.SParamType\x12\x33\n\x07Sparam2\x18\n \x01(\x0e\x32\".guiRpc.ExperimentSetup.SParamType\x12\x33\n\x07Sparam3\x18\x0b \x01(\x0e\x32\".guiRpc.ExperimentSetup.SParamType\x12\x33\n\x07Sparam4\x18\x0c \x01(\x0e\x32\".guiRpc.ExperimentSetup.SParamType\"9\n\nSParamType\x12\x07\n\x03Nop\x10\x00\x12\x07\n\x03S11\x10\x01\x12\x07\n\x03S21\x10\x02\x12\x07\n\x03S12\x10\x04\x12\x07\n\x03S22\x10\x08\x32{\n\x06GuiRpc\x12?\n\x0bstartSample\x12\x17.guiRpc.ExperimentSetup\x1a\x13.guiRpc.SampleArray\"\x00\x30\x01\x12\x30\n\x06labCmd\x12\x12.guiRpc.LabCommand\x1a\x10.guiRpc.CmdReply\"\x00\x42\x31\n\x1aio.grpc.labDataTool.guiRpcB\x0bGuiRpcProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)



_CMDREPLY_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='guiRpc.CmdReply.CmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Nop', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='statusStr', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='dataStr', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='dataBinary', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=152,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_CMDREPLY_CMDTYPE)

_SAMPLEARRAY_SPARAMTYPE = _descriptor.EnumDescriptor(
  name='SParamType',
  full_name='guiRpc.SampleArray.SParamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Nop', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S11', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S21', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S12', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S22', index=4, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=392,
  serialized_end=449,
)
_sym_db.RegisterEnumDescriptor(_SAMPLEARRAY_SPARAMTYPE)

_EXPERIMENTSETUP_SPARAMTYPE = _descriptor.EnumDescriptor(
  name='SParamType',
  full_name='guiRpc.ExperimentSetup.SParamType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Nop', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S11', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S21', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S12', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S22', index=4, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=392,
  serialized_end=449,
)
_sym_db.RegisterEnumDescriptor(_EXPERIMENTSETUP_SPARAMTYPE)


_BYTEBLOCK = _descriptor.Descriptor(
  name='ByteBlock',
  full_name='guiRpc.ByteBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_length', full_name='guiRpc.ByteBlock.data_length', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_bytes', full_name='guiRpc.ByteBlock.data_bytes', index=1,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=76,
)


_CMDREPLY = _descriptor.Descriptor(
  name='CmdReply',
  full_name='guiRpc.CmdReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdType', full_name='guiRpc.CmdReply.cmdType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmdReply', full_name='guiRpc.CmdReply.cmdReply', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CMDREPLY_CMDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=214,
)


_LABCOMMAND = _descriptor.Descriptor(
  name='LabCommand',
  full_name='guiRpc.LabCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='guiRpc.LabCommand.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=245,
)


_SAMPLEARRAY = _descriptor.Descriptor(
  name='SampleArray',
  full_name='guiRpc.SampleArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Meas_id', full_name='guiRpc.SampleArray.Meas_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sparam', full_name='guiRpc.SampleArray.Sparam', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='guiRpc.SampleArray.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ff', full_name='guiRpc.SampleArray.ff', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SAMPLEARRAY_SPARAMTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=449,
)


_EXPERIMENTSETUP = _descriptor.Descriptor(
  name='ExperimentSetup',
  full_name='guiRpc.ExperimentSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Meas_id', full_name='guiRpc.ExperimentSetup.Meas_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ENADataMode', full_name='guiRpc.ExperimentSetup.ENADataMode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NumberOfPoints', full_name='guiRpc.ExperimentSetup.NumberOfPoints', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freq_STAR', full_name='guiRpc.ExperimentSetup.freq_STAR', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freq_STOP', full_name='guiRpc.ExperimentSetup.freq_STOP', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freq_CENT', full_name='guiRpc.ExperimentSetup.freq_CENT', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freq_SPAN', full_name='guiRpc.ExperimentSetup.freq_SPAN', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataFormat', full_name='guiRpc.ExperimentSetup.dataFormat', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sparam1', full_name='guiRpc.ExperimentSetup.Sparam1', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sparam2', full_name='guiRpc.ExperimentSetup.Sparam2', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sparam3', full_name='guiRpc.ExperimentSetup.Sparam3', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sparam4', full_name='guiRpc.ExperimentSetup.Sparam4', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPERIMENTSETUP_SPARAMTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=898,
)

_CMDREPLY.fields_by_name['cmdType'].enum_type = _CMDREPLY_CMDTYPE
_CMDREPLY_CMDTYPE.containing_type = _CMDREPLY
_SAMPLEARRAY.fields_by_name['Sparam'].enum_type = _SAMPLEARRAY_SPARAMTYPE
_SAMPLEARRAY.fields_by_name['data'].message_type = _BYTEBLOCK
_SAMPLEARRAY.fields_by_name['ff'].message_type = _BYTEBLOCK
_SAMPLEARRAY_SPARAMTYPE.containing_type = _SAMPLEARRAY
_EXPERIMENTSETUP.fields_by_name['Sparam1'].enum_type = _EXPERIMENTSETUP_SPARAMTYPE
_EXPERIMENTSETUP.fields_by_name['Sparam2'].enum_type = _EXPERIMENTSETUP_SPARAMTYPE
_EXPERIMENTSETUP.fields_by_name['Sparam3'].enum_type = _EXPERIMENTSETUP_SPARAMTYPE
_EXPERIMENTSETUP.fields_by_name['Sparam4'].enum_type = _EXPERIMENTSETUP_SPARAMTYPE
_EXPERIMENTSETUP_SPARAMTYPE.containing_type = _EXPERIMENTSETUP
DESCRIPTOR.message_types_by_name['ByteBlock'] = _BYTEBLOCK
DESCRIPTOR.message_types_by_name['CmdReply'] = _CMDREPLY
DESCRIPTOR.message_types_by_name['LabCommand'] = _LABCOMMAND
DESCRIPTOR.message_types_by_name['SampleArray'] = _SAMPLEARRAY
DESCRIPTOR.message_types_by_name['ExperimentSetup'] = _EXPERIMENTSETUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ByteBlock = _reflection.GeneratedProtocolMessageType('ByteBlock', (_message.Message,), {
  'DESCRIPTOR' : _BYTEBLOCK,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.ByteBlock)
  })
_sym_db.RegisterMessage(ByteBlock)

CmdReply = _reflection.GeneratedProtocolMessageType('CmdReply', (_message.Message,), {
  'DESCRIPTOR' : _CMDREPLY,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.CmdReply)
  })
_sym_db.RegisterMessage(CmdReply)

LabCommand = _reflection.GeneratedProtocolMessageType('LabCommand', (_message.Message,), {
  'DESCRIPTOR' : _LABCOMMAND,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.LabCommand)
  })
_sym_db.RegisterMessage(LabCommand)

SampleArray = _reflection.GeneratedProtocolMessageType('SampleArray', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEARRAY,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.SampleArray)
  })
_sym_db.RegisterMessage(SampleArray)

ExperimentSetup = _reflection.GeneratedProtocolMessageType('ExperimentSetup', (_message.Message,), {
  'DESCRIPTOR' : _EXPERIMENTSETUP,
  '__module__' : 'guiRpc_pb2'
  # @@protoc_insertion_point(class_scope:guiRpc.ExperimentSetup)
  })
_sym_db.RegisterMessage(ExperimentSetup)


DESCRIPTOR._options = None

_GUIRPC = _descriptor.ServiceDescriptor(
  name='GuiRpc',
  full_name='guiRpc.GuiRpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=900,
  serialized_end=1023,
  methods=[
  _descriptor.MethodDescriptor(
    name='startSample',
    full_name='guiRpc.GuiRpc.startSample',
    index=0,
    containing_service=None,
    input_type=_EXPERIMENTSETUP,
    output_type=_SAMPLEARRAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='labCmd',
    full_name='guiRpc.GuiRpc.labCmd',
    index=1,
    containing_service=None,
    input_type=_LABCOMMAND,
    output_type=_CMDREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GUIRPC)

DESCRIPTOR.services_by_name['GuiRpc'] = _GUIRPC

# @@protoc_insertion_point(module_scope)
