# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import guiRpc_pb2 as guiRpc__pb2


class GuiRpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.startSample = channel.unary_stream(
        '/guiRpc.GuiRpc/startSample',
        request_serializer=guiRpc__pb2.ExperimentSetup.SerializeToString,
        response_deserializer=guiRpc__pb2.SampleArray.FromString,
        )
    self.labCmd = channel.unary_unary(
        '/guiRpc.GuiRpc/labCmd',
        request_serializer=guiRpc__pb2.LabCommand.SerializeToString,
        response_deserializer=guiRpc__pb2.CmdReply.FromString,
        )


class GuiRpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def startSample(self, request, context):
    """rpc getDataPlot( optionQuery) returns (stream SampleArray) {}

    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def labCmd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GuiRpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'startSample': grpc.unary_stream_rpc_method_handler(
          servicer.startSample,
          request_deserializer=guiRpc__pb2.ExperimentSetup.FromString,
          response_serializer=guiRpc__pb2.SampleArray.SerializeToString,
      ),
      'labCmd': grpc.unary_unary_rpc_method_handler(
          servicer.labCmd,
          request_deserializer=guiRpc__pb2.LabCommand.FromString,
          response_serializer=guiRpc__pb2.CmdReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'guiRpc.GuiRpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
