// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.



syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.labDataTool.guiRpc";
option java_outer_classname = "GuiRpcProto";
option objc_class_prefix = "HLW";

package guiRpc;


service GuiRpc {

  //rpc getDataPlot( optionQuery) returns (stream SampleArray) {}

  rpc startSample(ExperimentSetup) returns (stream SampleArray) {}

 // rpc labCmd(LabCommand) returns (STATUS) {}
}

message ByteBlock { 
  int32 data_length = 2;
  bytes data_bytes =1;
};

message STATUS {
  string ret = 1;
}



message SampleArray {
  enum SParamType {
    Nop = 0;
    S11 = 1;
    S21 = 2;
    S12 = 3;
    S22 = 4;
  }
  int32 Meas_id = 1;
  SParamType Sparam = 2;
  ByteBlock data = 3;
  ByteBlock ff = 4;
//  StreamBytes data = 5;

}

//'ENADataMode', 'NumberOfPoints', 'STAR', 'STOP',
//                  'CENT', 'SPAN', 'dataFromat' 
message ExperimentSetup {
  enum SParamType {
    Nop = 0;
    S11 = 1;
    S21 = 2;
    S12 = 4;
    S22 = 8;
  }

  int32 Meas_id = 1;
  int32 ENADataMode = 2;
  int32 NumberOfPoints =3;
  float freq_STAR =4;
  float freq_STOP =5;
  float freq_CENT =6;
  float freq_SPAN =7;
  int32 dataFormat =8;
  SParamType Sparam1 = 9;
  SParamType Sparam2 = 10;
  SParamType Sparam3 = 11;
  SParamType Sparam4 = 12;
  //repeated Material material = 5;
  
}  





