#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Sep 03, 2019 04:04:34 PM IDT  platform: Linux
#    Sep 08, 2019 05:21:41 PM IDT  platform: Linux
#    Sep 08, 2019 05:59:26 PM IDT  platform: Linux
#    Sep 10, 2019 11:14:47 AM IDT  platform: Linux
#   TODO - DB:Add fields for test parameters, materials
#    GUI  - remove field initial concen, 
#         - add options for view Graphs
#         - option for show DB
#         - Add Repeat button?
#         - Add read Text fields in Measurement press
  

import sys
import datetime
import rfSampleHub
import subprocess
import os
import messages

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global varRadio
    varRadio = tk.StringVar()
    global che48
    global comboStep_list, testType_list
    global radioBut
    che48 = tk.StringVar()
    testType_list = ['Electrolyte_in_Water']
    comboStep_list = ['Increment_Step','Decrement_Step']
    radioBut=1
    

def btnPlot():
    global w
    global rfSystem
    print('LabExper0_support. Plot the last Session Experiment')
    #rfSystem.getDataPlot('Session', 0)

    cwd = os.getcwd() + '/'
    print ("Openning hdfview with file:" + cwd + rfSystem.dbfile)
    proc = subprocess.Popen(["/usr/bin/hdfview",cwd+rfSystem.dbfile]) #, shell=True) 

def msgLabStep(i):
      global expr 
      if i==1:
        w.Text_Instruct.insert(tk.END, messages.fixedVolMsgStep[i].format(expr['material1'], expr['volumeExchange'] ))
      else:
        w.Text_Instruct.insert(tk.END, messages.fixedVolMsgStep[i])


def btnContinuePress():
    global expr 
    global state
    global w
    if state == 0:
       print("Error - Need to start session first")
       return
    print('LabExper0_support.btnContinuePress')
    if state != 2:
       print ("Wrong state")
       return
    w.Text_Instruct.delete('1.0', tk.END)
    msgLabStep(1)
    state = 1
    sys.stdout.flush()
    w.TextTestNum.delete("1.0",tk.END)
    expr['testNumber'] -= 1
    tidx = -expr['testNumber'] + expr['numM']+1
    if tidx > expr['numM']:
      #Done
      btnDonePress()
      return
    w.TextTestNum.insert("1.0",str(tidx)+"/"+str(expr['numM']))

    try:
      mat1Concen = float(expr['mat1Concen']) + 0.1
    except:
      print ("Wrong value in Material 1 concentration")
      mat1Concen = 0.0
    
    expr['mat1Concen']= str(mat1Concen)
    w.Text_Mat1Concen.delete(1.0, tk.END)
    w.Text_Mat1Concen.insert(1.0, str(expr['mat1Concen']))

def btnDonePress():
    global rfSystem
    global state
    global orig_color
    print('LabExper0_support.btnDonePress')
    sys.stdout.flush()
    state = 0
    rfSystem.maxsess += 1
    w.Text_Session.delete(1.0, tk.END)
    w.Text_Session.insert(1.0, str(rfSystem.maxsess))
    w.btnStart.configure(background=orig_color)

    w.Text_Instruct.delete('1.0', tk.END)
    w.Text_Instruct.insert('1.0', "Test Session End\n==========")

def btnMeasurePress():
    global state
    global rfSystem

    print('LabExper0_support.btnMeasurePress')
    sys.stdout.flush()
    if state == 0:
       print("Error - Need to start session first")
       return
    setUp['session'] =  rfSystem.maxsess
    setUp['material'] = expr['material1']
    setUp['concentrate'] = expr['initConcentrate']
    setUp['notes'] = expr['testNotes']
    rfSystem.startSample(setUp)
    
    if state == 1:
      msgLabStep(0)
    state = 2


def btnStartPress():
    global w
    global rfSystem
    global expr
    global state

    if state != 0:
      print ("Wrong State Error")
      return
    expr = {}
    print('LabExper0_support. Start the Experiment')
    sys.stdout.flush()
    expr['testerName'] = w.Text_Name.get("1.0","end-1c")
    print ("Tester Name:"+expr['testerName'])
    expr['testNotes'] = w.TextNotes.get("1.0","end-1c")
    print ("Test Notes:"+ expr['testNotes'])
    expr['material1'] = w.Text_Mat1.get("1.0","end-1c")
    print ("Material 1:"+expr['material1'])
    #expr['material2'] = w.Text_Mat2.get("1.0","end-1c")
    expr['stepUpDn'] = w.TCombobox_StepUpDn.get()
    print (w.TCombobox_StepUpDn.get())
    expr['testType'] = w.TCombobox_TestType.get()
    print(w.TCombobox_TestType.get())
    session = w.Text_Session.get("1.0","end-1c")
    print ("Session:" + w.Text_Session.get("1.0","end-1c"))
    expr['InitVolume'] =  w.Text_InitVol.get("1.0","end-1c")
    print ("initialVol:" + w.Text_InitVol.get("1.0","end-1c"))
    expr['numMeasures'] = w.Text_NumMeasures.get("1.0","end-1c")
    print (w.Text_NumMeasures.get("1.0","end-1c"))
    expr['concenDelta'] = w.Text_ConcenDelta.get("1.0","end-1c")
    print (w.Text_ConcenDelta.get("1.0","end-1c"))
    expr['initConcentrate'] = w.Text_InitConcen.get("1.0","end-1c")
    print (w.Text_InitConcen.get("1.0","end-1c"))
    expr['volumeExchange'] = w.Text_volExchange.get("1.0","end-1c")
    print (w.Text_volExchange.get("1.0","end-1c"))
    expr['mat1Concen'] = w.Text_Mat1Concen.get("1.0", "end-1c")
    try:
      rfSystem.maxsess = int(session)
      expr['testNumber'] = int(expr['numMeasures'])
      expr['numM'] = int(expr['numMeasures'])
    except:
        print ("Exception in number parse")
        pass
    w.TextTestNum.delete("1.0",tk.END)
    tidx = -expr['testNumber'] + expr['numM']+1
    w.TextTestNum.insert("1.0",str(tidx)+"/"+str(expr['numM']))
    for k, i in expr.items():
          if (type(i) == type(str)) and len(i) == 0:
              print ("Illegal parameter: " + k)
          else:
            if k=='numMeasures' or k=='initialVol':
              try:
                expr[k]= float(i)
              except ValueError:
                print ("Wrong value in {}-- Please Correct ".format(k))
                return
    state = 1
    w.Text_Instruct.delete('1.0', tk.END)
    w.Text_Instruct.insert(tk.END, messages.fixedVolMsgStart[0].format(session, expr['material1']))

    w.btnStart.configure(background="green")
 #    print (w.Checkbutton_DBOK.get("1.0","end-1c"))


def setFixedVol():
    print("Select fixed Vol")
    radioBut = 1
def setFixedConcen():
    print("Select fixed Concentrate")
    radioBut = 2


setUp = {
  'time' : None,
  'session': 0,
  'freqSt': '2GHZ',
  'freqEn': '3GHZ',
  'material' : 'water',
  'concentrate' : 0.8,
  'notes': ''
}

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    global rfSystem
    global varRadio
    global state 
    global orig_color 
    w = gui
    top_level = top
    root = top
    w.TCombobox_TestType.set(testType_list[0])
    w.TCombobox_StepUpDn.set(comboStep_list[0])
    varRadio.set(1)
    dateStr= datetime.datetime.now().strftime("%d/%m/%y")
    print (dateStr)
    w.Text_Date.insert(1.0, dateStr)
    orig_color = w.btnStart.cget("background")
    dataBaseName = "dataFile0"
    rfSystem = rfSampleHub.rfSampleHubHP( dataBaseName, True)
    rfSystem.maxsess += 1
    w.Text_Session.insert(1.0, str(rfSystem.maxsess))
    w.Text_Mat1Concen.insert(1.0, "0.0")
    w.Text_NumMeasures.insert("1.0", "10")

    state = 0
    #rfSystem = rfSampleHub( dataBaseName, True)
    ''' 
    try:
      rfSystem = rfSampleHub( dataBaseName = "dataFile0", MOCK=True)
    except:
      print ("rf sample hub failed")
      rfSystem = None
      #TODO - Add setting of the Checkbox
    '''


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import LabExperPage
    LabExperPage.vp_start_gui()





