#############################################################################
# Generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#  Sep 10, 2019 11:19:04 AM IDT  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 8 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

    menu .pop49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop49" "Popupmenu1" vTcl:WidgetProc "" 1
    .pop49 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label Options 

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 622x814+494+103
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3185 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Experiment Page"
    vTcl:DefineAlias "$top" "ExperForm" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Notes 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "ExperForm" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Test :} 
    vTcl:DefineAlias "$top.lab44" "Label2" vTcl:WidgetProc "ExperForm" 1
    text $top.tex45 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 226 \
        -wrap word 
    .top42.tex45 configure -font "TkTextFont"
    .top42.tex45 insert end text
    vTcl:DefineAlias "$top.tex45" "TextNotes" vTcl:WidgetProc "ExperForm" 1
    text $top.tex46 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 166 \
        -wrap word 
    .top42.tex46 configure -font "TkTextFont"
    .top42.tex46 insert end text
    vTcl:DefineAlias "$top.tex46" "Text_Name" vTcl:WidgetProc "ExperForm" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Tester Name} 
    vTcl:DefineAlias "$top.lab48" "Label3" vTcl:WidgetProc "ExperForm" 1
    button $top.but49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command btnStartPress -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text Start 
    vTcl:DefineAlias "$top.but49" "btnStart" vTcl:WidgetProc "ExperForm" 1
    listbox $top.lis54 \
        -background white -font TkFixedFont -foreground {#000000} -height -6 \
        -highlightcolor black -selectbackground {#c4c4c4} \
        -selectforeground black -width -136 
    .top42.lis54 configure -font "TkFixedFont"
    .top42.lis54 insert end text
    vTcl:DefineAlias "$top.lis54" "Listbox1" vTcl:WidgetProc "ExperForm" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Date: 
    vTcl:DefineAlias "$top.lab45" "Label4" vTcl:WidgetProc "ExperForm" 1
    ttk::combobox $top.tCo46 \
        -values {'Electrolyte in Water'} -font TkTextFont -foreground {} \
        -background {#000000} -takefocus {} 
    vTcl:DefineAlias "$top.tCo46" "TCombobox_TestType" vTcl:WidgetProc "ExperForm" 1
    set site_3_0 $top.m47
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $site_3_0 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -label Options 
    text $top.tex48 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -state disabled \
        -width 106 -wrap word 
    .top42.tex48 configure -font "TkTextFont"
    .top42.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "Text_Date" vTcl:WidgetProc "ExperForm" 1
    text $top.tex49 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 106 \
        -wrap word 
    .top42.tex49 configure -font "TkTextFont"
    .top42.tex49 insert end text
    vTcl:DefineAlias "$top.tex49" "Text_Session" vTcl:WidgetProc "ExperForm" 1
    label $top.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Session#: 
    vTcl:DefineAlias "$top.lab52" "Label4_2" vTcl:WidgetProc "ExperForm" 1
    label $top.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Material_1 
    vTcl:DefineAlias "$top.lab53" "Label5" vTcl:WidgetProc "ExperForm" 1
    label $top.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Material_2 
    vTcl:DefineAlias "$top.lab54" "Label6" vTcl:WidgetProc "ExperForm" 1
    label $top.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Material_3 
    vTcl:DefineAlias "$top.lab55" "Label6_3" vTcl:WidgetProc "ExperForm" 1
    label $top.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Material_4 
    vTcl:DefineAlias "$top.lab56" "Label6_4" vTcl:WidgetProc "ExperForm" 1
    text $top.tex57 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 86 \
        -wrap word 
    .top42.tex57 configure -font "TkTextFont"
    .top42.tex57 insert end text
    vTcl:DefineAlias "$top.tex57" "Text_Mat1" vTcl:WidgetProc "ExperForm" 1
    label $top.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Procedure 
    vTcl:DefineAlias "$top.lab58" "Label_Procudure" vTcl:WidgetProc "ExperForm" 1
    ttk::combobox $top.tCo59 \
        -values {'Increment_Step' 'Decrement Step'} -font TkTextFont \
        -foreground {} -background {#000000} -takefocus {} 
    vTcl:DefineAlias "$top.tCo59" "TCombobox_StepUpDn" vTcl:WidgetProc "ExperForm" 1
    label $top.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Initial Volume (mL):} 
    vTcl:DefineAlias "$top.lab60" "Label7" vTcl:WidgetProc "ExperForm" 1
    text $top.tex61 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex61 configure -font "TkTextFont"
    .top42.tex61 insert end text
    vTcl:DefineAlias "$top.tex61" "Text_InitVol" vTcl:WidgetProc "ExperForm" 1
    text $top.tex62 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 86 \
        -wrap word 
    .top42.tex62 configure -font "TkTextFont"
    .top42.tex62 insert end text
    vTcl:DefineAlias "$top.tex62" "Text_Mat2" vTcl:WidgetProc "ExperForm" 1
    label $top.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Num Measures:} 
    vTcl:DefineAlias "$top.lab63" "Label8" vTcl:WidgetProc "ExperForm" 1
    label $top.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Pepeto Volume Exch (mL):} 
    vTcl:DefineAlias "$top.lab64" "Label8_8" vTcl:WidgetProc "ExperForm" 1
    text $top.tex65 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex65 configure -font "TkTextFont"
    .top42.tex65 insert end text
    vTcl:DefineAlias "$top.tex65" "Text_volExchange" vTcl:WidgetProc "ExperForm" 1
    text $top.tex66 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex66 configure -font "TkTextFont"
    .top42.tex66 insert end text
    vTcl:DefineAlias "$top.tex66" "Text_NumMeasures" vTcl:WidgetProc "ExperForm" 1
    label $top.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Concentration Delta:} 
    vTcl:DefineAlias "$top.lab67" "Label8_9" vTcl:WidgetProc "ExperForm" 1
    text $top.tex68 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex68 configure -font "TkTextFont"
    .top42.tex68 insert end text
    vTcl:DefineAlias "$top.tex68" "Text_ConcenDelta" vTcl:WidgetProc "ExperForm" 1
    label $top.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Initial Concentration:} 
    vTcl:DefineAlias "$top.lab69" "Label7_11" vTcl:WidgetProc "ExperForm" 1
    text $top.tex70 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex70 configure -font "TkTextFont"
    .top42.tex70 insert end text
    vTcl:DefineAlias "$top.tex70" "Text_InitConcen" vTcl:WidgetProc "ExperForm" 1
    radiobutton $top.rad43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text {Fixed Volume Chnage} \
        -value 1 -variable varRadio 
    vTcl:DefineAlias "$top.rad43" "Radiobutton1" vTcl:WidgetProc "ExperForm" 1
    radiobutton $top.rad44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text {Fixed Concentrate Change} \
        -value 2 -variable varRadio 
    vTcl:DefineAlias "$top.rad44" "Radiobutton2" vTcl:WidgetProc "ExperForm" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Step_Up/Down 
    vTcl:DefineAlias "$top.lab46" "Label_Step" vTcl:WidgetProc "ExperForm" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {DB Connect:} 
    vTcl:DefineAlias "$top.lab47" "Label9" vTcl:WidgetProc "ExperForm" 1
    checkbutton $top.che48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -state disabled -text OK \
        -variable che48 
    vTcl:DefineAlias "$top.che48" "Checkbutton_DBOK" vTcl:WidgetProc "ExperForm" 1
    text $top.tex43 \
        -background white -font TkTextFont -foreground black -height 182 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 536 \
        -wrap word 
    .top42.tex43 configure -font "TkTextFont"
    .top42.tex43 insert end text
    vTcl:DefineAlias "$top.tex43" "Text_Instruct" vTcl:WidgetProc "ExperForm" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -text {Concentrate mEq/L} 
    vTcl:DefineAlias "$top.lab49" "Label8_1" vTcl:WidgetProc "ExperForm" 1
    text $top.tex50 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 56 \
        -wrap word 
    .top42.tex50 configure -font "TkTextFont"
    .top42.tex50 insert end text
    vTcl:DefineAlias "$top.tex50" "Text_Mat1Concen" vTcl:WidgetProc "ExperForm" 1
    text $top.tex51 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 56 \
        -wrap word 
    .top42.tex51 configure -font "TkTextFont"
    .top42.tex51 insert end text
    vTcl:DefineAlias "$top.tex51" "Text_Mat2Concen" vTcl:WidgetProc "ExperForm" 1
    button $top.but58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command btnMeasurePress -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text Measure 
    vTcl:DefineAlias "$top.but58" "btnMeasure" vTcl:WidgetProc "ExperForm" 1
    text $top.tex59 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 86 \
        -wrap word 
    .top42.tex59 configure -font "TkTextFont"
    .top42.tex59 insert end text
    vTcl:DefineAlias "$top.tex59" "Text_Mat3" vTcl:WidgetProc "ExperForm" 1
    text $top.tex60 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 86 \
        -wrap word 
    .top42.tex60 configure -font "TkTextFont"
    .top42.tex60 insert end text
    vTcl:DefineAlias "$top.tex60" "Text_Mat4" vTcl:WidgetProc "ExperForm" 1
    text $top.tex63 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 56 \
        -wrap word 
    .top42.tex63 configure -font "TkTextFont"
    .top42.tex63 insert end text
    vTcl:DefineAlias "$top.tex63" "Text_Mat3Concen" vTcl:WidgetProc "ExperForm" 1
    text $top.tex64 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 56 \
        -wrap word 
    .top42.tex64 configure -font "TkTextFont"
    .top42.tex64 insert end text
    vTcl:DefineAlias "$top.tex64" "Text_Mat4Concen" vTcl:WidgetProc "ExperForm" 1
    button $top.but65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command btnContinuePress -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text Continue 
    vTcl:DefineAlias "$top.but65" "btnContinue" vTcl:WidgetProc "ExperForm" 1
    button $top.but66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -command btnDonePress -font TkDefaultFont \
        -foreground {#000000} -highlightcolor black -text Done 
    vTcl:DefineAlias "$top.but66" "btnDone" vTcl:WidgetProc "ExperForm" 1
    label $top.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Test# 
    vTcl:DefineAlias "$top.lab68" "Label10" vTcl:WidgetProc "ExperForm" 1
    text $top.tex71 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex71 configure -font "TkTextFont"
    .top42.tex71 insert end text
    vTcl:DefineAlias "$top.tex71" "TextTestNum" vTcl:WidgetProc "ExperForm" 1
    text $top.tex72 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex72 configure -font "TkTextFont"
    .top42.tex72 insert end text
    vTcl:DefineAlias "$top.tex72" "TextCurrentConc1" vTcl:WidgetProc "ExperForm" 1
    label $top.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -text {Current (mEq/L)} 
    vTcl:DefineAlias "$top.lab74" "Label8_2" vTcl:WidgetProc "ExperForm" 1
    text $top.tex75 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex75 configure -font "TkTextFont"
    .top42.tex75 insert end text
    vTcl:DefineAlias "$top.tex75" "TextCurrentConc2" vTcl:WidgetProc "ExperForm" 1
    text $top.tex76 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex76 configure -font "TkTextFont"
    .top42.tex76 insert end text
    vTcl:DefineAlias "$top.tex76" "TextCurrentConc3" vTcl:WidgetProc "ExperForm" 1
    text $top.tex77 \
        -background white -font TkTextFont -foreground black -height 22 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 46 \
        -wrap word 
    .top42.tex77 configure -font "TkTextFont"
    .top42.tex77 insert end text
    vTcl:DefineAlias "$top.tex77" "TextCurrentConc4" vTcl:WidgetProc "ExperForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 60 -width 56 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 10 -y 100 -width 76 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex45 \
        -in $top -x 70 -y 70 -width 226 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex46 \
        -in $top -x 125 -y 25 -width 166 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 9 -y 21 -width 86 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 70 -y 470 -width 109 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lis54 \
        -in $top -x 450 -y 220 -width -136 -relwidth 0 -height -6 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 378 -y 32 -width 66 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo46 \
        -in $top -x 90 -y 110 -width 137 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex48 \
        -in $top -x 440 -y 30 -width 106 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex49 \
        -in $top -x 440 -y 60 -width 106 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.lab52 \
        -in $top -x 367 -y 62 -width 76 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 10 -y 150 -width 76 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 10 -y 180 -width 76 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 10 -y 210 -width 76 -height 18 -anchor nw \
        -bordermode ignore 
    place $top.lab56 \
        -in $top -x 10 -y 240 -width 76 -height 18 -anchor nw \
        -bordermode ignore 
    place $top.tex57 \
        -in $top -x 100 -y 150 -width 86 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 10 -y 270 -width 76 -height 38 -anchor nw \
        -bordermode ignore 
    place $top.tCo59 \
        -in $top -x 140 -y 320 -width 157 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 20 -y 372 -width 116 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex61 \
        -in $top -x 185 -y 370 -width 46 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex62 \
        -in $top -x 100 -y 180 -width 86 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.lab63 \
        -in $top -x 21 -y 431 -width 96 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 9 -y 397 -width 176 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex65 \
        -in $top -x 184 -y 400 -width 46 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.tex66 \
        -in $top -x 184 -y 430 -width 46 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.lab67 \
        -in $top -x 240 -y 400 -width 146 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex68 \
        -in $top -x 390 -y 402 -width 46 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.lab69 \
        -in $top -x 244 -y 372 -width 146 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex70 \
        -in $top -x 388 -y 371 -width 46 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.rad43 \
        -in $top -x 120 -y 280 -anchor nw -bordermode ignore 
    place $top.rad44 \
        -in $top -x 320 -y 280 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x -10 -y 310 -width 126 -relwidth 0 -height 38 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 410 -y 90 -anchor nw -bordermode ignore 
    place $top.che48 \
        -in $top -x 490 -y 90 -anchor nw -bordermode ignore 
    place $top.tex43 \
        -in $top -x 40 -y 523 -width 536 -relwidth 0 -height 182 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 254 -y 109 -width 136 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex50 \
        -in $top -x 286 -y 151 -width 56 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex51 \
        -in $top -x 286 -y 183 -width 56 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 422 -y 738 -width 109 -height 38 -anchor nw \
        -bordermode ignore 
    place $top.tex59 \
        -in $top -x 100 -y 210 -width 86 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.tex60 \
        -in $top -x 99 -y 240 -width 86 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.tex63 \
        -in $top -x 286 -y 212 -width 56 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.tex64 \
        -in $top -x 285 -y 242 -width 56 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.but65 \
        -in $top -x 70 -y 740 -width 109 -height 38 -anchor nw \
        -bordermode ignore 
    place $top.but66 \
        -in $top -x 420 -y 470 -width 109 -height 38 -anchor nw \
        -bordermode ignore 
    place $top.lab68 \
        -in $top -x 220 -y 750 -anchor nw -bordermode ignore 
    place $top.tex71 \
        -in $top -x 270 -y 748 -width 46 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tex72 \
        -in $top -x 439 -y 152 -width 46 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.lab74 \
        -in $top -x 408 -y 110 -width 136 -height 28 -anchor nw \
        -bordermode ignore 
    place $top.tex75 \
        -in $top -x 439 -y 183 -width 46 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.tex76 \
        -in $top -x 438 -y 213 -width 46 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.tex77 \
        -in $top -x 439 -y 243 -width 46 -height 22 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

