#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24
#  in conjunction with Tcl version 8.6
#    Sep 03, 2019 04:06:16 PM IDT  platform: Linux
#    Sep 09, 2019 01:20:46 PM IDT  platform: Linux
#    Sep 10, 2019 11:19:21 AM IDT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import LabExperPage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    LabExperPage_support.set_Tk_var()
    top = ExperForm (root)
    LabExperPage_support.init(root, top)
    root.mainloop()

w = None
def create_ExperForm(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    LabExperPage_support.set_Tk_var()
    top = ExperForm (w)
    LabExperPage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ExperForm():
    global w
    w.destroy()
    w = None

class ExperForm:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family {DejaVu Sans} -size 8 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("622x814+494+103")
        top.title("Experiment Page")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.016, rely=0.074, height=38, width=56)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Notes''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.016, rely=0.123, height=38, width=76)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Test :''')

        self.TextNotes = tk.Text(top)
        self.TextNotes.place(relx=0.113, rely=0.086, relheight=0.027
                , relwidth=0.363)
        self.TextNotes.configure(background="white")
        self.TextNotes.configure(font="TkTextFont")
        self.TextNotes.configure(selectbackground="#c4c4c4")
        self.TextNotes.configure(width=226)
        self.TextNotes.configure(wrap="word")

        self.Text_Name = tk.Text(top)
        self.Text_Name.place(relx=0.201, rely=0.031, relheight=0.027
                , relwidth=0.267)
        self.Text_Name.configure(background="white")
        self.Text_Name.configure(font="TkTextFont")
        self.Text_Name.configure(selectbackground="#c4c4c4")
        self.Text_Name.configure(width=166)
        self.Text_Name.configure(wrap="word")

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.008, rely=0.025, height=28, width=86)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Tester Name''')

        self.btnStart = tk.Button(top)
        self.btnStart.place(relx=0.113, rely=0.577, height=38, width=109)
        self.btnStart.configure(activebackground="#f9f9f9")
        self.btnStart.configure(command=LabExperPage_support.btnStartPress)
        self.btnStart.configure(text='''Start''')

        '''
        self.btnGraph = tk.Button(top)
        self.btnGraph.place(relx=0.517, rely=0.849, height=38, width=109)
        self.btnGraph.configure(activebackground="#f9f9f9")
        self.btnGraph.configure(command=LabExper0_support.btnPlot)
        self.btnGraph.configure(text=''''Plot'''')
        '''

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.723, rely=0.27, relheight=0.001
                , relwidth=0.002)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(selectbackground="#c4c4c4")
        self.Listbox1.configure(width=-136)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.603, rely=0.037, height=18, width=66)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''Date:''')

        self.TCombobox_TestType = ttk.Combobox(top)
        self.TCombobox_TestType.place(relx=0.145, rely=0.135, relheight=0.022
                , relwidth=0.22)
        self.value_list = ['Electrolyte,in,Water',]
        self.TCombobox_TestType.configure(values=self.value_list)
        self.TCombobox_TestType.configure(background="#000000")
        self.TCombobox_TestType.configure(takefocus="")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                font="TkMenuFont",
                foreground="#000000",
                label="Options")

        self.Text_Date = tk.Text(top)
        self.Text_Date.place(relx=0.707, rely=0.037, relheight=0.027
                , relwidth=0.17)
        self.Text_Date.configure(background="white")
        self.Text_Date.configure(font="TkTextFont")
        self.Text_Date.configure(selectbackground="#c4c4c4")
#        self.Text_Date.configure(state='disabled')
        self.Text_Date.configure(width=106)
        self.Text_Date.configure(wrap="word")
#        dateStr= datetime.datetime.now().strftime("%d/%m/%y")
#        print (dateStr)
#        self.Text_Date.insert(1.0, dateStr)

        self.Text_Session = tk.Text(top)
        self.Text_Session.place(relx=0.707, rely=0.074, relheight=0.027
                , relwidth=0.17)
        self.Text_Session.configure(background="white")
        self.Text_Session.configure(font="TkTextFont")
        self.Text_Session.configure(selectbackground="#c4c4c4")
#        self.Text_Session.configure(state='disabled')
#        self.Text_Session.configure(state='enabled')
        self.Text_Session.configure(width=106)
        self.Text_Session.configure(wrap="word")

        self.Label4_2 = tk.Label(top)
        self.Label4_2.place(relx=0.587, rely=0.074, height=18, width=76)
        self.Label4_2.configure(activebackground="#f9f9f9")
        self.Label4_2.configure(text='''Session#:''')

        self.Label5 = tk.Label(top)
        self.Label5.place(relx=0.016, rely=0.184, height=18, width=76)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''Material_1''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.016, rely=0.221, height=18, width=76)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(text='''Material_2''')

        self.Label6_3 = tk.Label(top)
        self.Label6_3.place(relx=0.016, rely=0.258, height=18, width=76)
        self.Label6_3.configure(activebackground="#f9f9f9")
        self.Label6_3.configure(text='''Material_3''')

        self.Label6_4 = tk.Label(top)
        self.Label6_4.place(relx=0.016, rely=0.295, height=18, width=76)
        self.Label6_4.configure(activebackground="#f9f9f9")
        self.Label6_4.configure(text='''Material_4''')

        self.Text_Mat1 = tk.Text(top)
        self.Text_Mat1.place(relx=0.161, rely=0.184, relheight=0.027
                , relwidth=0.138)
        self.Text_Mat1.configure(background="white")
        self.Text_Mat1.configure(font="TkTextFont")
        self.Text_Mat1.configure(selectbackground="#c4c4c4")
        self.Text_Mat1.configure(width=86)
        self.Text_Mat1.configure(wrap="word")

        self.Label_Procudure = tk.Label(top)
        self.Label_Procudure.place(relx=0.016, rely=0.332, height=38, width=76)
        self.Label_Procudure.configure(activebackground="#f9f9f9")
        self.Label_Procudure.configure(text='''Procedure''')

        self.TCombobox_StepUpDn = ttk.Combobox(top)
        self.TCombobox_StepUpDn.place(relx=0.225, rely=0.393, relheight=0.022
                , relwidth=0.252)
        self.value_list = ['Increment_Step','Decrement,Step',]
        self.TCombobox_StepUpDn.configure(values=self.value_list)
        self.TCombobox_StepUpDn.configure(background="#000000")
        self.TCombobox_StepUpDn.configure(takefocus="")

        self.Label7 = tk.Label(top)
        self.Label7.place(relx=0.032, rely=0.455, height=18, width=116)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(text='''Initial Volume (mL):''')

        self.Text_InitVol = tk.Text(top)
        self.Text_InitVol.place(relx=0.297, rely=0.455, relheight=0.027
                , relwidth=0.074)
        self.Text_InitVol.configure(background="white")
        self.Text_InitVol.configure(font="TkTextFont")
        self.Text_InitVol.configure(selectbackground="#c4c4c4")
        self.Text_InitVol.configure(width=46)
        self.Text_InitVol.configure(wrap="word")

        self.Text_Mat2 = tk.Text(top)
        self.Text_Mat2.place(relx=0.161, rely=0.221, relheight=0.027
                , relwidth=0.138)
        self.Text_Mat2.configure(background="white")
        self.Text_Mat2.configure(font="TkTextFont")
        self.Text_Mat2.configure(selectbackground="#c4c4c4")
        self.Text_Mat2.configure(width=86)
        self.Text_Mat2.configure(wrap="word")
        self.Text_Mat2.configure(state='disabled')

        self.Label8 = tk.Label(top)
        self.Label8.place(relx=0.032, rely=0.528, height=18, width=96)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(text='''Num Measures:''')

        self.Label8_8 = tk.Label(top)
        self.Label8_8.place(relx=0.008, rely=0.485, height=28, width=176)
        self.Label8_8.configure(activebackground="#f9f9f9")
        self.Label8_8.configure(text='''Pepeto Volume Exch (mL):''')
        self.Label8_8.configure(width=176)

        self.Text_volExchange = tk.Text(top)
        self.Text_volExchange.place(relx=0.289, rely=0.491, relheight=0.027
                , relwidth=0.074)
        self.Text_volExchange.configure(background="white")
        self.Text_volExchange.configure(font="TkTextFont")
        self.Text_volExchange.configure(selectbackground="#c4c4c4")
        self.Text_volExchange.configure(width=46)
        self.Text_volExchange.configure(wrap="word")

        self.Text_NumMeasures = tk.Text(top)
        self.Text_NumMeasures.place(relx=0.289, rely=0.528, relheight=0.027
                , relwidth=0.074)
        self.Text_NumMeasures.configure(background="white")
        self.Text_NumMeasures.configure(font="TkTextFont")
        self.Text_NumMeasures.configure(selectbackground="#c4c4c4")
        self.Text_NumMeasures.configure(width=46)
        self.Text_NumMeasures.configure(wrap="word")

        self.Label8_9 = tk.Label(top)
        self.Label8_9.place(relx=0.386, rely=0.491, height=28, width=146)
        self.Label8_9.configure(activebackground="#f9f9f9")
        self.Label8_9.configure(text='''Concentration Delta:''')

        self.Text_ConcenDelta = tk.Text(top)
        self.Text_ConcenDelta.place(relx=0.627, rely=0.491, relheight=0.027
                , relwidth=0.074)
        self.Text_ConcenDelta.configure(background="white")
        self.Text_ConcenDelta.configure(font="TkTextFont")
        self.Text_ConcenDelta.configure(selectbackground="#c4c4c4")
        self.Text_ConcenDelta.configure(width=46)
        self.Text_ConcenDelta.configure(wrap="word")

        self.Label7_11 = tk.Label(top)
        self.Label7_11.place(relx=0.386, rely=0.455, height=18, width=146)
        self.Label7_11.configure(activebackground="#f9f9f9")
        self.Label7_11.configure(text='''Initial Concentration:''')

        self.Text_InitConcen = tk.Text(top)
        self.Text_InitConcen.place(relx=0.619, rely=0.455, relheight=0.027
                , relwidth=0.074)
        self.Text_InitConcen.configure(background="white")
        self.Text_InitConcen.configure(font="TkTextFont")
        self.Text_InitConcen.configure(selectbackground="#c4c4c4")
        self.Text_InitConcen.configure(width=46)
        self.Text_InitConcen.configure(wrap="word")

        self.Radiobutton1 = tk.Radiobutton(top)
        self.Radiobutton1.place(relx=0.193, rely=0.344, relheight=0.025
                , relwidth=0.256)
        self.Radiobutton1.configure(activebackground="#f9f9f9")
        self.Radiobutton1.configure(justify='left')
        self.Radiobutton1.configure(text='''Fixed Volume Chnage''')
        self.Radiobutton1.configure(value="1")
        self.Radiobutton1.configure(variable=LabExperPage_support.varRadio)

        self.Radiobutton2 = tk.Radiobutton(top)
        self.Radiobutton2.place(relx=0.514, rely=0.344, relheight=0.025
                , relwidth=0.302)
        self.Radiobutton2.configure(activebackground="#f9f9f9")
        self.Radiobutton2.configure(justify='left')
        self.Radiobutton2.configure(text='''Fixed Concentrate Change''')
        self.Radiobutton2.configure(value="2")
        self.Radiobutton2.configure(variable=LabExperPage_support.varRadio)

        self.Label_Step = tk.Label(top)
        self.Label_Step.place(relx=-0.016, rely=0.381, height=38, width=126)
        self.Label_Step.configure(activebackground="#f9f9f9")
        self.Label_Step.configure(text='''Step_Up/Down''')
        self.Label_Step.configure(width=126)

        self.Label9 = tk.Label(top)
        self.Label9.place(relx=0.659, rely=0.111, height=18, width=79)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(text='''DB Connect:''')

        self.Checkbutton_DBOK = tk.Checkbutton(top)
        self.Checkbutton_DBOK.place(relx=0.788, rely=0.111, relheight=0.025
                , relwidth=0.068)
        self.Checkbutton_DBOK.configure(activebackground="#f9f9f9")
        self.Checkbutton_DBOK.configure(justify='left')
        self.Checkbutton_DBOK.configure(state='disabled')
        self.Checkbutton_DBOK.configure(text='''OK''')
        self.Checkbutton_DBOK.configure(variable=LabExperPage_support.che48)

        self.Text_Instruct = tk.Text(top)
        self.Text_Instruct.place(relx=0.064, rely=0.639, relheight=0.224
                , relwidth=0.862)
        self.Text_Instruct.configure(background="white")
        self.Text_Instruct.configure(font="TkTextFont")
        self.Text_Instruct.configure(selectbackground="#c4c4c4")
        self.Text_Instruct.configure(width=536)
        self.Text_Instruct.configure(wrap="word")
        self.Text_Instruct.configure(bg="skyblue")

        self.Label8_1 = tk.Label(top)
        self.Label8_1.place(relx=0.402, rely=0.129, height=28, width=136)
        self.Label8_1.configure(activebackground="#f9f9f9")
        self.Label8_1.configure(font=font9)
        self.Label8_1.configure(text='''Concentrate mEq/L''')
        self.Label8_1.configure(width=136)

        self.Text_Mat1Concen = tk.Text(top)
        self.Text_Mat1Concen.place(relx=0.458, rely=0.184, relheight=0.027
                , relwidth=0.09)
        self.Text_Mat1Concen.configure(background="white")
        self.Text_Mat1Concen.configure(font="TkTextFont")
        self.Text_Mat1Concen.configure(selectbackground="#c4c4c4")
        self.Text_Mat1Concen.configure(width=56)
        self.Text_Mat1Concen.configure(wrap="word")

        self.Text_Mat2Concen = tk.Text(top)
        self.Text_Mat2Concen.place(relx=0.458, rely=0.221, relheight=0.027
                , relwidth=0.09)
        self.Text_Mat2Concen.configure(background="white")
        self.Text_Mat2Concen.configure(font="TkTextFont")
        self.Text_Mat2Concen.configure(selectbackground="#c4c4c4")
        self.Text_Mat2Concen.configure(width=56)
        self.Text_Mat2Concen.configure(wrap="word")

        self.btnMeasure = tk.Button(top)
        self.btnMeasure.place(relx=0.675, rely=0.903, height=38, width=109)
        self.btnMeasure.configure(activebackground="#f9f9f9")
        self.btnMeasure.configure(command=LabExperPage_support.btnMeasurePress)
        self.btnMeasure.configure(text='''Measure''')

        self.Text_Mat3 = tk.Text(top)
        self.Text_Mat3.place(relx=0.161, rely=0.258, relheight=0.027
                , relwidth=0.138)
        self.Text_Mat3.configure(background="white")
        self.Text_Mat3.configure(font="TkTextFont")
        self.Text_Mat3.configure(selectbackground="#c4c4c4")
        self.Text_Mat3.configure(width=86)
        self.Text_Mat3.configure(wrap="word")

        self.Text_Mat4 = tk.Text(top)
        self.Text_Mat4.place(relx=0.153, rely=0.295, relheight=0.027
                , relwidth=0.138)
        self.Text_Mat4.configure(background="white")
        self.Text_Mat4.configure(font="TkTextFont")
        self.Text_Mat4.configure(selectbackground="#c4c4c4")
        self.Text_Mat4.configure(width=86)
        self.Text_Mat4.configure(wrap="word")

        self.Text_Mat3Concen = tk.Text(top)
        self.Text_Mat3Concen.place(relx=0.458, rely=0.258, relheight=0.027
                , relwidth=0.09)
        self.Text_Mat3Concen.configure(background="white")
        self.Text_Mat3Concen.configure(font="TkTextFont")
        self.Text_Mat3Concen.configure(selectbackground="#c4c4c4")
        self.Text_Mat3Concen.configure(width=56)
        self.Text_Mat3Concen.configure(wrap="word")

        self.Text_Mat4Concen = tk.Text(top)
        self.Text_Mat4Concen.place(relx=0.458, rely=0.295, relheight=0.027
                , relwidth=0.09)
        self.Text_Mat4Concen.configure(background="white")
        self.Text_Mat4Concen.configure(font="TkTextFont")
        self.Text_Mat4Concen.configure(selectbackground="#c4c4c4")
        self.Text_Mat4Concen.configure(width=56)
        self.Text_Mat4Concen.configure(wrap="word")

        self.btnContinue = tk.Button(top)
        self.btnContinue.place(relx=0.113, rely=0.909, height=38, width=109)
        self.btnContinue.configure(activebackground="#f9f9f9")
        self.btnContinue.configure(command=LabExperPage_support.btnContinuePress)
        self.btnContinue.configure(text='''Continue''')

        self.btnDone = tk.Button(top)
        self.btnDone.place(relx=0.675, rely=0.577, height=38, width=109)
        self.btnDone.configure(activebackground="#f9f9f9")
        self.btnDone.configure(command=LabExperPage_support.btnDonePress)
        self.btnDone.configure(text='''Done''')

        self.Label10 = tk.Label(top)
        self.Label10.place(relx=0.354, rely=0.921, height=18, width=39)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(text='''Test#''')

        self.TextTestNum = tk.Text(top)
        self.TextTestNum.place(relx=0.434, rely=0.915, relheight=0.027
                , relwidth=0.074)
        self.TextTestNum.configure(background="white")
        self.TextTestNum.configure(font="TkTextFont")
        self.TextTestNum.configure(selectbackground="#c4c4c4")
        self.TextTestNum.configure(width=46)
        self.TextTestNum.configure(wrap="word")

        self.TextCurrentConc1 = tk.Text(top)
        self.TextCurrentConc1.place(relx=0.699, rely=0.184, relheight=0.027
                , relwidth=0.074)
        self.TextCurrentConc1.configure(background="white")
        self.TextCurrentConc1.configure(font="TkTextFont")
        self.TextCurrentConc1.configure(selectbackground="#c4c4c4")
        self.TextCurrentConc1.configure(width=46)
        self.TextCurrentConc1.configure(wrap="word")

        self.Label8_2 = tk.Label(top)
        self.Label8_2.place(relx=0.651, rely=0.135, height=28, width=136)
        self.Label8_2.configure(activebackground="#f9f9f9")
        self.Label8_2.configure(font=font9)
        self.Label8_2.configure(text='''Current (mEq/L)''')

        self.TextCurrentConc2 = tk.Text(top)
        self.TextCurrentConc2.place(relx=0.699, rely=0.221, relheight=0.027
                , relwidth=0.074)
        self.TextCurrentConc2.configure(background="white")
        self.TextCurrentConc2.configure(font="TkTextFont")
        self.TextCurrentConc2.configure(selectbackground="#c4c4c4")
        self.TextCurrentConc2.configure(width=46)
        self.TextCurrentConc2.configure(wrap="word")

        self.TextCurrentConc3 = tk.Text(top)
        self.TextCurrentConc3.place(relx=0.699, rely=0.258, relheight=0.027
                , relwidth=0.074)
        self.TextCurrentConc3.configure(background="white")
        self.TextCurrentConc3.configure(font="TkTextFont")
        self.TextCurrentConc3.configure(selectbackground="#c4c4c4")
        self.TextCurrentConc3.configure(width=46)
        self.TextCurrentConc3.configure(wrap="word")

        self.TextCurrentConc4 = tk.Text(top)
        self.TextCurrentConc4.place(relx=0.699, rely=0.295, relheight=0.027
                , relwidth=0.074)
        self.TextCurrentConc4.configure(background="white")
        self.TextCurrentConc4.configure(font="TkTextFont")
        self.TextCurrentConc4.configure(selectbackground="#c4c4c4")
        self.TextCurrentConc4.configure(width=46)
        self.TextCurrentConc4.configure(wrap="word")

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.add_command(
                activebackground="#ececec",
                activeforeground="#000000",
                background="#d9d9d9",
                compound="left",
                font="TkMenuFont",
                foreground="#000000",
                label="Options")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





